### ISSUE TITLE
UnionLib and Optifine crash

### ISSUE THREAD

**Issue by nekomaster** [Stereowalker/UnionLib#1]
MC 1.18.1 w/ Forge 39.0.0

UnionLib-1.18.1-6.0.0
preview_OptiFine_1.18.1_HD_U_H4_pre1

Sorry if this has been brought up, and also sorry if you don't care to fix the issue (I know some mod authors don't care to deal with Optifine)

Just having UnionLib and optifine in the same mod folder together with nothing else causes the game to crash immidately.

Heres some log files if that helps.

[debug.log](https://github.com/Stereowalker/UnionLib/files/7697865/debug.log)
[latest.log](https://github.com/Stereowalker/UnionLib/files/7697866/latest.log)

PS This is a new fresh install of MC 1.18.1 and Forge 39.0.0

**Comment by nekomaster** [comment]
It'll suck if this mod and optifine can't work because I would like to use that survival mod you made with thirst and sleep stuff. I dunno if I can just dump optifine for the performance gains and shader support.

**Comment by Stereowalker** [comment]
This was a really big issue, but it's been fixed and we can finally put this behind us
