### ISSUE TITLE
[bug]Stuck game 5-60second when Character die  and reborn 

### ISSUE THREAD

**Issue by darkaaa** [Stereowalker/UnionLib#6]
Version is fabric. 1.18.1
Tired 6.1.1  to  6.1.5  they all  stuck the game and no reponse when player die and  reborn until 10-60second later.

**Comment by qznfbnj** [comment]
Me too but for forge-40.1.51.
I use UnionLib-1.18.2-7.1.1, and suicide will cause game frozen for 20+ seconds, without the Internet it will not
parts of logs: https://gist.github.com/qznfbnj/b625daccabc2df0f8c48784f319a5a82

**Comment by Stereowalker** [comment]
Thanks, I now understand the full scope of the issue
