### ISSUE TITLE
Modrinth or Allow CF API

### ISSUE THREAD

**Issue by Merith-TK** [Stereowalker/UnionLib#8]
![image](https://user-images.githubusercontent.com/10422110/173147474-ed0a64a5-cfe2-4c6c-99e5-97bc7418f633.png)

I use Packwiz for my modpacks and this makes it difficult for my players to just download and play

please make an release on modrith OR please flick this switch on the curseforge page
![image](https://user-images.githubusercontent.com/10422110/173147610-366828dc-a972-494b-8f29-9970ab548f96.png)

**Comment by Stereowalker** [comment]
It totally skipped my mind, but I've already enabled 3rd party distribution on UnionLib. It's basically a library mod and shouldn't be restricted to CurseForge.

**Comment by Merith-TK** [comment]
thank you!

**Comment by Stereowalker** [comment]
You're welcome
